[package]
name = "tonic"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core-preview = "=0.3.0-alpha.18"
futures-util-preview = "=0.3.0-alpha.18"
tonic-macros = { path = "../tonic-macros" }
tracing = "0.1"
http = "0.1.14"
base64 = "0.10"
bytes = "0.4.7"
prost = "0.5"
percent-encoding = "1.0.1"
tower-service = "=0.3.0-alpha.1"
tokio-codec = "=0.2.0-alpha.4"
async-stream = { git = "https://github.com/tokio-rs/async-stream" }
http-body = "0.2.0-alpha.1"
pin-project = "0.4.0-alpha.2"

# optional
hyper = { git = "https://github.com/hyperium/hyper", optional = true}
tokio = { version = "=0.2.0-alpha.4", default-features = false, features = ["tcp"], optional = true }
tower-make = "=0.1.0-alpha.2"
tower-reconnect = { path = "../../tower/tower-reconnect", optional = true }
tower-buffer = { path = "../../tower/tower-buffer", optional = true }

# openssl
tokio-openssl = { version = "=0.4.0-alpha.4", optional = true }
openssl = { version = "0.10", optional = true }

# rustls
tokio-rustls = { path = "../../tokio-rustls", optional = true }

[features]
default = ["transport"]
transport = [
    "hyper",
    "tower-reconnect",
    "tower-buffer",
    "tokio",
    "openssl-1",
]
openssl-1 = ["openssl", "tokio-openssl"]
rustls = ["tokio-rustls"]
