[package]
name = "tonic"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

[dependencies]
futures-core-preview = "=0.3.0-alpha.18"
futures-util-preview = "=0.3.0-alpha.18"
tonic-macros = { path = "../tonic-macros" }
tracing = "0.1"
http = "0.1.14"
base64 = "0.10"
bytes = "0.4.7"
prost = "0.5"
percent-encoding = "1.0.1"
tower-service = "=0.3.0-alpha.1"
tokio-codec = "=0.2.0-alpha.4"
async-stream = { git = "https://github.com/tokio-rs/async-stream" }
http-body = "0.2.0-alpha.1"
pin-project = "=0.4.0-alpha.7"

# optional
hyper = { version = "=0.13.0-alpha.1", optional = true }
tokio = { version = "=0.2.0-alpha.4", default-features = false, features = ["tcp"], optional = true }
tower-make = "=0.1.0-alpha.2"
tower-reconnect = { git = "https://github.com/tower-rs/tower", branch = "lucio/update-reconnect-buffer", optional = true }
tower-buffer = { git = "https://github.com/tower-rs/tower", branch = "lucio/update-reconnect-buffer", optional = true }
tower-balance = { git = "https://github.com/tower-rs/tower", branch = "lucio/update-balance", optional = true }
tower-load = { git = "https://github.com/tower-rs/tower", branch = "lucio/update-balance", optional = true }
tower-discover = { git = "https://github.com/tower-rs/tower", branch = "lucio/update-balance", optional = true }

# openssl
tokio-openssl = { version = "=0.4.0-alpha.4", optional = true }
openssl = { version = "0.10", optional = true }

# rustls
tokio-rustls = { version = "0.12.0-alpha.2", optional = true }

[features]
default = ["transport"]
transport = [
    "hyper",
    "tower",
    "tokio",
    "native-tls",
]
tower = [
    "tower-reconnect",
    "tower-buffer",
    "tower-balance",
    "tower-load",
    "tower-discover"
]
native-tls = ["openssl", "tokio-openssl"]
# rustls = ["tokio-rustls"]
