[package]
name = "tonic"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core-preview = "=0.3.0-alpha.18"
futures-util-preview = "=0.3.0-alpha.18"
tonic-macros = { path = "../tonic-macros" }
tracing = "0.1"
http = "0.1.14"
base64 = "0.10"
bytes = "0.4.7"
prost = "0.5"
percent-encoding = "1.0.1"
tower-service = "=0.3.0-alpha.1"
tokio-codec = "=0.2.0-alpha.4"
# async-stream = "0.1.0"
async-stream = { path = "../../async-stream/async-stream" }
http-body = "0.2.0-alpha.1"
pin-project = "0.4.0-alpha.2"
hyper = { git = "https://github.com/hyperium/hyper", optional = true}

# tower
tower-reconnect = { path = "../../tower/tower-reconnect", optional = true }
tower-buffer = { path = "../../tower/tower-buffer", optional = true }

[features]
default = ["transport"]
transport = ["hyper", "tower-reconnect", "tower-buffer"]
