[package]
name = "tonic-examples"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "helloworld-server"
path = "src/helloworld/server.rs"

# [[bin]]
# name = "helloworld-client"
# path = "src/helloworld/client.rs"

[dependencies]
tonic = { path = "../tonic" }
tower-h2 = { path = "../tower-h2" }
futures-preview = { version = "=0.3.0-alpha.17", default-features = false, features = ["alloc"]}
tokio = "=0.2.0-alpha.1"
prost = "0.5"
prost-derive = "0.5"
bytes = "0.4"

[build-dependencies]
tonic-build = { path = "../tonic-build" }
