name: Test Rust project
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [nightly]

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Run check
      run: cargo check --all --all-features --all-targets
    - name: Run tests
      run: cargo test --all
    - name: Run interop tests
      run: ./tonic-interop/test.sh
