name: test
on: [push,pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Run check
      run: cargo check --all
    - name: Run check with no default features
      run: cargo check --all --no-default-features
    - name: Run tests
      run: cargo test --all
